# Configuration for Musique training
model:
  name: "meta-llama/Meta-Llama-3-8B"
  pad_token: "eos_token"

dataset:
  name: "uva-irlab/musique"
  config: "full"
  split: "train"
  preprocess_function: "preprocess_musique"

grpo:
  batch_size: 2
  mini_batch_size: 1
  learning_rate: 1.41e-5
  adap_kl_ctrl: true
  init_kl_coef: 0.2
  group_reward_mode: "relative"
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.1

training:
  output_dir: "./grpo_musique"
  num_train_epochs: 1
  logging_steps: 1
  save_steps: 10
  fp16: true

generation:
  min_length: -1
  top_k: 0.0
  top_p: 0.9
  do_sample: true
  max_new_tokens: 100
  temperature: 0.7

reward:
  function: "compute_musique_reward"
