model_id: "meta-llama/Llama-3.2-3B"
dataset_name: "awinml/factscore_unlabelled_alpaca_13b_retrieval"
split: "train"
output_dir: "./outputs/supervised_finetuning/p_tuning/factscore"

num_train_epochs: 3
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
save_strategy: "epoch"
logging_steps: 10

num_virtual_tokens: 20
encoder_hidden_size: 128
